# Definimos la lista de hosts
---
lista_host:
    - name: 10.144.37.5
    cmd: "show running-config"
    platform: ios
    - name: 10.144.37.6
    cmd: "show interface status"
    platform: iosxr
    
